feat: initial implementation
FlowingCode/LocaleComboBox pull request #1
Opened 2024-07-31 14:20 UTC by elPeiretti

2024-08-01 13:20 UTC, javier-godoy requested changes

2024-08-01 13:20 UTC, javier-godoy commented on src/main/java/com/flowingcode/vaadin/addons/localecombobox/LocaleComboBox.java
> +            .sorted((l1, l2) -> l1.getDisplayName().compareTo(l2.getDisplayName())).toList());
`getDisplayName` uses the default locale of the JVM. Maybe it should be `l1.getDisplayName(l1)` , `l2.getDisplayName(l2)`. We can discuss this in an issue.

2024-08-01 13:20 UTC, javier-godoy commented on src/main/java/com/flowingcode/vaadin/addons/localecombobox/LocaleComboBox.java
> +        .<Locale>of("<vaadin-horizontal-layout class=\"" + ITEM_LAYOUT_CLASS_NAME + "\">"
Since the minimum Java version is 17, you can use multiline text blocks, which don't require escaping `"`:

```
of("""
"a" "b"
""");

2024-08-01 14:23 UTC, javier-godoy commented on src/main/java/com/flowingcode/vaadin/addons/localecombobox/LocaleComboBox.java
> +            .sorted((l1, l2) -> l1.getDisplayName().compareTo(l2.getDisplayName())).toList());
Comment overriden by https://github.com/FlowingCode/LocaleComboBox/issues/2

2024-08-05 15:13 UTC, paodb commented
Hi, it looks good to me. One thing is that when I tried to test it locally I run into some issue 
![image](https://github.com/user-attachments/assets/49e56352-6217-47ae-9999-5cf072498060)
Line 263 from pom file should be removed if no folder src/main/resources/META-INF/resources exists.
Afer that everything worked okay.

2024-08-05 15:17 UTC, paodb commented
Also note that some updates have been done to AddonsStarter 24 since you've created this repo, so you might need to do some updates:
- License https://github.com/FlowingCode/AddonStarter24/blob/master/LICENSE that was recently updated (remove first lines).
- Readme file: Special Configuration when using Spring changed, see https://github.com/FlowingCode/AddonStarter24/pull/41/files and remove reference to vaadin directory repository https://github.com/FlowingCode/AddonStarter24/pull/39/files

2024-08-05 17:25 UTC, javier-godoy requested changes
Requested changes per https://github.com/FlowingCode/LocaleComboBox/pull/1#issuecomment-2269316587 and https://github.com/FlowingCode/LocaleComboBox/pull/1#issuecomment-2269323796

2024-08-06 19:06 UTC, paodb approved these changes
LGTM

2024-08-06 19:07 UTC, javier-godoy approved these changes

2024-08-06 19:08 UTC, merged